pub mod auth_tracking;
pub mod cleanup_subscriber;
pub mod email;
pub mod file_cleanup;
pub mod filter;
pub mod inflight_thumbnails;
pub mod metadata;
pub mod pdf_cache;
pub mod plugin;
pub mod rate_limiter;
pub mod read_progress;
pub mod settings;
pub mod task_listener;
pub mod task_metrics;
pub mod thumbnail;

pub use auth_tracking::AuthTrackingService;
pub use cleanup_subscriber::CleanupEventSubscriber;
pub use file_cleanup::{CleanupStats, FileCleanupService, OrphanedFileType};
pub use filter::FilterService;
pub use inflight_thumbnails::InflightThumbnailTracker;
pub use pdf_cache::{CacheStats, CleanupResult, PdfPageCache};
pub use rate_limiter::RateLimiterService;
pub use read_progress::ReadProgressService;
pub use settings::SettingsService;
pub use task_listener::TaskListener;
pub use task_metrics::TaskMetricsService;
pub use thumbnail::ThumbnailService;

pub use plugin::encryption::CredentialEncryption;
