name: Build and Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - ".gitea/workflows/docs.yaml"
      - "docs/**"
      - "web/openapi.json"
  pull_request:
    branches:
      - main
    paths:
      - ".gitea/workflows/docs.yaml"
      - "docs/**"
      - "web/openapi.json"
  workflow_dispatch: # Allow manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Build and push Docker image for docs (push to main only)
  docker-docs:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Registry FQDN Setup
        id: registry
        run: |
          registry=${{ github.server_url }}
          echo "registry=${registry##http*://}" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.registry.outputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ steps.registry.outputs.registry }}/${{ github.repository }}-docs
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push docs Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docs/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
