//! Komga-compatible API handlers
//!
//! This module contains request handlers for the Komga-compatible API.
//! Handlers are implemented in separate modules by resource type.

pub mod books;
pub mod libraries;
pub mod pages;
pub mod read_progress;
pub mod series;
pub mod stubs;
pub mod users;

// Re-export handlers for convenience
pub use books::{
    download_book_file, get_book, get_book_thumbnail, get_books_ondeck, get_next_book,
    get_previous_book, search_books,
};
pub use libraries::{get_library, get_library_thumbnail, list_libraries};
pub use pages::{get_page, get_page_thumbnail, list_pages};
pub use read_progress::{
    delete_progress, get_progression, mark_series_as_read, mark_series_as_unread, put_progression,
    update_progress,
};
pub use series::{
    get_series, get_series_books, get_series_new, get_series_thumbnail, get_series_updated,
    list_series, search_series,
};
pub use stubs::{
    list_age_ratings, list_authors_v2, list_collections, list_genres, list_languages,
    list_publishers, list_readlists, list_series_release_dates, list_tags,
};
pub use users::get_current_user;

// Re-export utoipa path macros for OpenAPI documentation
// These are generated by utoipa for the API docs and may not be used directly
#[doc(hidden)]
#[allow(unused_imports)]
pub use books::{
    __path_download_book_file, __path_get_book, __path_get_book_thumbnail, __path_get_books_ondeck,
    __path_get_next_book, __path_get_previous_book, __path_search_books,
};
#[doc(hidden)]
#[allow(unused_imports)]
pub use libraries::{__path_get_library, __path_get_library_thumbnail, __path_list_libraries};
#[doc(hidden)]
#[allow(unused_imports)]
pub use pages::{__path_get_page, __path_get_page_thumbnail, __path_list_pages};
#[doc(hidden)]
#[allow(unused_imports)]
pub use read_progress::{
    __path_delete_progress, __path_get_progression, __path_mark_series_as_read,
    __path_mark_series_as_unread, __path_put_progression, __path_update_progress,
};
#[doc(hidden)]
#[allow(unused_imports)]
pub use series::{
    __path_get_series, __path_get_series_books, __path_get_series_new, __path_get_series_thumbnail,
    __path_get_series_updated, __path_list_series, __path_search_series,
};
#[doc(hidden)]
#[allow(unused_imports)]
pub use stubs::{
    __path_list_age_ratings, __path_list_authors_v2, __path_list_collections, __path_list_genres,
    __path_list_languages, __path_list_publishers, __path_list_readlists,
    __path_list_series_release_dates, __path_list_tags,
};
#[doc(hidden)]
#[allow(unused_imports)]
pub use users::__path_get_current_user;
