import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import fs from "fs";
import path from "path";

// Load API sidebar if it exists (generated by docusaurus-plugin-openapi-docs)
// If not generated yet, return empty array to allow build to succeed
const apiSidebarPath = path.join(__dirname, "docs/api/sidebar.ts");

let apiSidebarItems: SidebarsConfig[string] = [];

if (fs.existsSync(apiSidebarPath)) {
  apiSidebarItems = require("./docs/api/sidebar.ts").default;
}

export default apiSidebarItems;
